version: '3'

networks:
    asus:

services:
    site:
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: nginx
        ports:
            - 81:81
        volumes:
            - .:/var/www/html:delegated
        depends_on:
            - php
            - redis
            - mysql
            - mailhog
        networks:
            - asus
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: rennyka_db
            MYSQL_USER: rennyka107
            MYSQL_PASSWORD: rennyka107
            MYSQL_ROOT_PASSWORD: rennyka107
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./dockerfiles/mysql:/var/lib/mysql
        networks:
            - asus

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: php
        volumes:
            - .:/var/www/html:delegated
        networks:
            - asus

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        networks:
            - asus

    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: composer
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        user: asus
        entrypoint: [ 'composer', '--ignore-platform-reqs' ]
        networks:
            - asus

    npm:
        image: node:16.5.0
        container_name: npm
        volumes:
            - .:/var/www/html
        ports:
            - 5000:5000
            - 3001:3001
        working_dir: /var/www/html
        entrypoint: [ 'npm' ]
        networks:
            - asus

    artisan:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: artisan
        volumes:
            - .:/var/www/html:delegated
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: [ 'php', '/var/www/html/artisan' ]
        networks:
            - asus

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - asus
